sonar.projectKey=inventario-frontend
sonar.projectName=Portami Inventario Frontend
sonar.sourceEncoding=UTF-8

sonar.sources=src
sonar.tests=src/tests
sonar.test.inclusions=src/tests/**/*.test.ts,src/tests/**/*.test.tsx
sonar.exclusions=coverage/**,dist/**,node_modules/**,public/**

sonar.typescript.tsconfigPath=tsconfig.json
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.coverage.exclusions=src/tests/**,src/main.tsx,src/theme.ts,src/types/**/*.d.ts

