sonar.organization=portami
sonar.projectKey=Portami_inventario-frontend
sonar.projectName=Portami Inventario Frontend
sonar.sourceEncoding=UTF-8

sonar.sources=src
sonar.tests=src
sonar.test.inclusions=src/**/*.test.ts,src/**/*.test.tsx

sonar.typescript.tsconfigPath=tsconfig.json
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.coverage.exclusions=src/app/main.tsx,src/app/theme.ts,src/**/*.d.ts,src/shared/testing/**

sonar.exclusions=coverage/**,dist/**,node_modules/**,public/**
