name: Pull request workflow
on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
      - labeled
      - unlabeled

permissions:
  contents: read
  packages: read

jobs:
  get-tag:
    if: ${{ !github.event.pull_request.draft }}
    runs-on: ubuntu-latest
    outputs:
      sha_short: ${{ steps.short-commit-hash.outputs.short }}
    steps:
      - name: Get short commit hash
        id: short-commit-hash
        uses: prompt/actions-commit-hash@v3
        with:
          commit: '${{ github.sha }}'

  validate:
    needs: get-tag
    uses: ./.github/workflows/_validate.yaml

  sonar:
    needs:
      - get-tag
      - validate
    uses: ./.github/workflows/_sonar.yaml
    secrets: inherit
    with:
      sonar-version: ${{ needs.get-tag.outputs.sha_short }}-SNAPSHOT

  build-push:
    if: ${{ contains(github.event.pull_request.labels.*.name, 'deploy') }}
    needs:
      - get-tag
      - validate
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/_build-push.yaml
    with:
      tag: ${{ needs.get-tag.outputs.sha_short }}

  update-infra:
    needs:
      - get-tag
      - build-push
    uses: ./.github/workflows/_update-infra.yaml
    secrets: inherit
    with:
      environment: staging
      tag: ${{ needs.get-tag.outputs.sha_short }}