name: Sonar

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  sonar:
    uses: ./.github/workflows/reusable-sonar.yml
    with:
      sonar-version: ${{ github.sha }}
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

